### ISSUE TITLE
WiThrottle Timeout

### ISSUE THREAD

**Issue by conaito** [positron96/LocoNetControlStation#10]
i played a bit with Engine Driver and found out that if i not make anything for a while (lets say 5 minutes) the it looks like the connection lost (or lost the locomotive slot?).. then the throttle activity make nothing (only after set again the Address of locomotive). I also tested it with another WiThrottle device.. same here. Any idea here?

**Comment by conaito** [comment]
Same is also if i use a Loconet Throttle. After a while of not drive the Locomotive the Throttle looks like lost the Slot for the Locomotive. Then i must re-take the Adress for the Loco to get it back to work. Same is on WiThrottle usage)

**Comment by positron96** [comment]
Hi. I've fixed a couple of bugs related to WiThrottle heartbeats, you might want to check whether the latest version has the problem fixed.

**Comment by conaito** [comment]
i be happy to do it tomorrow. can you view me the changes in any way?
Am 24. Nov. 2021, 18:29 +0100 schrieb Paul Melnikov ***@***.***>:

**Comment by positron96** [comment]
Well, the bugfixes are intermixed with refactoring and other features. https://github.com/positron96/LocoNetControlStation/commit/17ed7f8f633aad619b4f4f7aae9a49b22eae5720

**Comment by positron96** [comment]
I'll close it assuming it is fixed. Reopen if needed.
