### ISSUE TITLE
Loconet switch

### ISSUE THREAD

**Issue by conaito** [positron96/LocoNetControlStation#11]
I attached the Uhlenbrock IB Switch but it seems to not work. Looks like it wait for some switch settings from command station:

I][WiThrottle.cpp:91] begin(): WiThrottleServer::begin
*WM: [3] unloading
onPacket: SW_STATE(BC) 00 00 43 
onPacket: SW_STATE(BC) 00 00 43 
onPacket: SW_STATE(BC) 00 00 43

Any idea how i get it work?

**Comment by conaito** [comment]
if i use command station as sniffer (by use a Loconet command station) i get follow serial on pluging the IB Switch:

[I][WiThrottle.cpp:91] begin(): WiThrottleServer::begin
*WM: [3] unloading
onPacket: LONG_ACK(B4) 3C 50 27 
onPacket: SW_STATE(BC) 01 00 42
onPacket: LONG_ACK(B4) 3C 30 47
onPacket: SW_STATE(BC) 07 00 44 
onPacket: LONG_ACK(B4) 3C 30 47

**Comment by positron96** [comment]
Hi, thanks for the report and sniffer dump.

Please describe what your setup is. What loconet devices are connected to the bus apart from ESP32 and IB Switch? A switch decoder itself? Another command station?

**Comment by positron96** [comment]
Did it start to work after you fixed the hardware?

**Comment by conaito** [comment]
no still not work.
Am 10. Nov. 2021, 10:52 +0100 schrieb Paul Melnikov ***@***.***>:

**Comment by conaito** [comment]
as i see you started turnout roster. it send to withrottle on connect with engine driver. does it also send out on loconet? may here is the issue?
Am 10. Nov. 2021, 10:52 +0100 schrieb Paul Melnikov ***@***.***>:

**Comment by positron96** [comment]
Well then, my question still stands. What is your setup? I actually don't know what command station needs to do when your switch controller talks to switch decoder. It is my understanding that it should do nothing, and it is implemented this way. Is your decoder connected via LocoNet or DCC?

**Comment by conaito** [comment]
The IB Switch is just a board from Uhlenbrock with buttons (to can use as switches for turnouts as example). Thats what you need to know?

**Comment by positron96** [comment]
Please describe what your setup is. What loconet devices are connected to the bus apart from ESP32 and IB Switch? A switch decoder itself? Another command station?

**Comment by conaito** [comment]
1) only command station and the IB Switch
or
2) Command Station, Daisy 2 (Uhlenbrock) hand throttle and IB Switch
(Uhlenbrock too)

both same..

Am Mo., 15. Nov. 2021 um 15:42 Uhr schrieb Paul Melnikov <
***@***.***>:

**Comment by positron96** [comment]
So, are your turnout decoders connected via DCC? The command station does not forward switch commands from LocoNet to DCC. I have no DCC decoders and so have no way to test if such forwarding works. Also, without decoders I have no need for this feature.

**Comment by conaito** [comment]
No, at this moment i have no turnout decoders on DCC. The IB Switch is just
for Loconet. There can Loconet addresses can set for switch anything as
example turnouts. But it will get no answers on plug on the loconet
interface as it does if i use a other loconet command station as you can
see on top (dump).

Am Mo., 15. Nov. 2021 um 15:59 Uhr schrieb Paul Melnikov <
***@***.***>:

**Comment by positron96** [comment]
Yes, your other command station answers to LocoNet switch requests (on behalf of DCC decoders that can't talk back). This command station does not process switch commands in any way.

**Comment by conaito** [comment]
ah now i understand. is there any way to implement it to get it near to a full support command station like that?
Am 15. Nov. 2021, 16:37 +0100 schrieb Paul Melnikov ***@***.***>:

**Comment by conaito** [comment]
just to make sure.. on the other command station setup also no DCC decoders attached
Am 15. Nov. 2021, 16:37 +0100 schrieb Paul Melnikov ***@***.***>:

**Comment by positron96** [comment]
No, it's not that difficult. There is some work already done in the form of turnout roster. 
The good thing about open-source is that you can always implement what you need yourself.

**Comment by conaito** [comment]
Can you may give me a small start idea with code to know where i can go on
? This would really be great

Am Di., 16. Nov. 2021 um 04:17 Uhr schrieb Paul Melnikov <
***@***.***>:

**Comment by positron96** [comment]
Processing of LocoNet messages is done in `LocoNetSlotManager` in `processMessage` (there is a big `switch` on opcodes), you'd need to add `case` of the messages you need. As you have found, turnout roster is handled by `CommandStation`,  Methods `getTurnouts` and `turnoutToggle` and `turnoutAction` would be needed to react of recieved LocoNet messages.

**Comment by positron96** [comment]
Closing in favor of #16
