### ISSUE TITLE
Wifi settings

### ISSUE THREAD

**Issue by conaito** [positron96/LocoNetControlStation#12]
are there any chance to change wifi settings after connected Wifi network. May a link/url to can change it?

**Comment by positron96** [comment]
Just erase the stored WiFi data. 
This can be accomplished by calling `wifiManager.erase()` after declaring wifiManager on line 127.

**Comment by conaito** [comment]
but there is no webpage or similar available to do it without coding?

Am Mo., 15. Nov. 2021 um 15:48 Uhr schrieb Paul Melnikov <
***@***.***>:

**Comment by positron96** [comment]
If ESP32 can't connect to WiFi with stored settings (e.g. there are no stored settings), then it will start a webpage. The webpage is only there to connect to WiFi, so after the esp32 connects to WiFi, there is no webpage. You can also turn off the WiFi router to force esp32 to start config webpage.
