### ISSUE TITLE
Function F1-F4, bug in DCC.cpp

### ISSUE THREAD

**Issue by alsacian** [positron96/LocoNetControlStation#20]
Hi, I found a problem when activating functions F1 to F4,
bug in line 91 of DCC.cpp :
I changed to : fn = (fn & 0x1)<<4 | (fn & 0x1E)>>1; instead of fn = (fn & 0x1)<<4 | (fn & 0x1E)<<1;
Thanks for the good work.
Best regards

**Comment by positron96** [comment]
Great! Thank you very much for finding that.
