### ISSUE TITLE
Can't compile with esp-idf 3.2.0

### ISSUE THREAD

**Issue by lucadentella** [positron96/LocoNetControlStation#7]
Hi

it seems that espressif platform 3.2.0 has a compile warning in "esp32-hal-spi.c".
If you have the "-Werror" build flag in platformio.ini you cannot compile the code, see platformio/platform-espressif32#528.

I solved removing the flag...
Thanks

**Comment by positron96** [comment]
Thanks for reporting. 
Do you happen to know a way to disable the flag for framework itself but retain it for project's source? I've stumbled upon this issue in other projects, but have not found a solution.

**Comment by lucadentella** [comment]
Unfortunately no, it seems that PlatformIO uses the same flags to compile everything (framework + project source)

**Comment by positron96** [comment]
Apparently, there is `src_build_flags` instead of `build_flags`.

**Comment by lucadentella** [comment]
thanks, it works!
